version: '3.6'

services:
  telegram-bot-dev:
    container_name: telegram-bot-dev
    image: python:telegram-bot-dev
    build:
      context: .
    volumes:
      - ./project:/project
    environment:
      - TOK_NUM=1
    networks:
      - telegram-bot-dev

networks:
  telegram-bot-dev:
    name: telegram-bot-dev
    driver: bridge
