version: '3.6'

services:
  telegram-bot:
    container_name: telegram-bot
    image: python:telegram-bot-dev
    build:
      context: .
    volumes:
      - ./project:/project
    # ports:
    #   - '0.0.0.0:3302:3306'
    networks:
      - telegram-bot-dev


networks:
  telegram-bot-dev:
    name: telegram-bot-dev
    driver: bridge
